import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Montserrat } from "next/font/google";
import antdTheme from "../antd-theme";

import "./globals.css";
import { ConfigProvider } from "antd";
const montserrat = Montserrat({ subsets: ["latin"] });
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ConfigProvider theme={antdTheme}>
        <body className={montserrat.className}>{children}</body>
      </ConfigProvider>
    </html>
  );
}
